---
- name: Playbook for Creating VPC
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check host
      ping:

- name: Create VPC 
  include: vpc.yaml

- name: Run Sec Group 
  include: sec-group.yaml

- name: Run Private Playbook
  include: private-subnet.yaml

- name: Run Public Playbook
  include: pub-subnets.yaml

- name: Add igw
  import_playbook: igw.yaml

- name: Add Public RT 
  import_playbook: rt_pub.yaml

- name: Add Private RT 
  import_playbook: rt_priv.yaml

- name: Run ASG
  import_playbook: auto_sg.yaml

- name: added ELB 
  import_playbook: elastic-lb.yaml